#!/bin/bash
echo "📋 INSTRUÇÕES FINAIS - CRAFTIVA.EU"
echo "=================================="
echo ""
echo "O GitHub Actions está a fazer o deploy automaticamente."
echo "Enquanto isso, configura o domínio:"
echo ""
echo "🔥 FIREBASE CONSOLE:"
echo "1. Abre: https://console.firebase.google.com/project/craftiva-eu/hosting"
echo "2. Clica 'Add custom domain'"
echo "3. Escreve: craftiva.eu"
echo "4. Continue"
echo ""
echo "📝 NAMECHEAP DNS:"
echo "1. Abre: https://ap.www.namecheap.com/domains/list/"
echo "2. craftiva.eu → Manage → Advanced DNS"
echo "3. APAGA registos A/CNAME existentes"
echo "4. ADICIONA:"
echo ""
echo "   Type: A Record"
echo "   Host: @"
echo "   Value: 151.101.1.195"
echo ""
echo "   Type: A Record"
echo "   Host: @"  
echo "   Value: 151.101.65.195"
echo ""
echo "5. Save All Changes"
echo ""
echo "⏳ Aguarda 30min-2h para DNS propagar"
echo ""
echo "✅ DEPOIS: craftiva.eu estará ONLINE!"
